---

- include: "nginx/install/repository.yml"
  tags:    [nginx, install, repository]

- include: "nginx/install/dependencies.yml"
  tags:    [nginx, install, dependencies]

- include: "nginx/install/package.yml"
  tags:    [nginx, install, repository]

- include: "nginx/get/service/status.yml"
  tags:    [nginx, get, service, status]

- include: "nginx/create/sites-available/directory.yml"
  tags:    [nginx, create, sites-available, directory]

- include: "nginx/create/sites-enabled/directory.yml"
  tags:    [nginx, create, sites-enabled, directory]

- include: "nginx/create/log/directory.yml"
  tags:    [nginx, create, log, directory]

- include: "nginx/create/vhosts.yml"
  tags:    [nginx, create, vhosts]

- include: "nginx/create/http-auth.yml"
  tags:    [nginx, create, auth]

#- include: "nginx/disable/default/vhost.yml"
#  tags:    [nginx, disable, default, vhost]
#
#- include: "nginx/remove/default/vhost.yml"
#  tags:    [nginx, disable, default, vhost]

- include: "nginx/disable/vhosts.yml"
  tags:    [nginx, disable, vhosts]

- include: "nginx/enable/vhosts.yml"
  tags:    [nginx, enable, vhosts]

- include: "nginx/set/configuration.yml"
  tags:    [nginx, set, configuration]

- include: "nginx/service/start.yml"
  when:    '( (not nginx_service_is_running|bool) and (nginx_service_status == "started") )'
  tags:    [nginx, service, start]

- include: "nginx/service/stop.yml"
  when:    '( (nginx_service_is_running|bool) and (nginx_service_status == "stopped") )'
  tags:    [nginx, service, stop]
