---

- name: "nginx:set:configuration | Copy the nginx configuration file "
  template:
    src:  '{{ role_path + "/templates/nginx/nginx.conf.j2" }}'
    dest: '{{ nginx_path_config_main }}'
  notify:
    - 'service:nginx:reload'
