---

- name: "nginx:install:dependencies | Ensure all nginx and ansible dependencies present"
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'python-passlib'        # for htpasswd ansible module