require 'rake'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  if ENV['SERVERSPEC_PATH']
    t.pattern = ENV['SERVERSPEC_PATH'] + '/*_spec.rb'
  else 
    exit 0
  end
end

task :default => :spec
